### ISSUE TITLE
implement expand/collapse user's items feature

### ISSUE THREAD

**Issue by eLeontev** [eLeontev/board#10]
As user I want to expand/collapse items each of user in the grid on click to arrow icon.

Acceptance criterias: 
After click on arrow icon the list of items of the user should be expanded/collapsed 
The arrow icon should be changed to original position (should be rotated) use the flag `isCollapsed` can be replaced to `isExpanded if it needs`

**Comment by cjdeleon62** [comment]
@eLeontev, I can take this ticket if you're okay with it.

**Comment by eLeontev** [comment]
@cjdeleon62 ok, lets start) I'd implemented key for it in `ArrowIconContainer` please, use it if it comfortoble for you, and will assign it to you

**Comment by andrewgreenh** [comment]
@cjdeleon62 are you still working on this? If not, I'd like to take a shot.

**Comment by eLeontev** [comment]
@andreasgruenh thanks for your help
